# Write this file into ~/.config/wireplumber/wireplumber.conf.d/
# and restart WirePlumber daemon:
#     systemctl --user restart wireplumber
#
# ── MOTU UltraLite Mk5 Altset mapping ─────────────────────────────────────
#
# cat /proc/asound/card0/stream0
#   |_ Altset 1 → 22ch playback / 20ch capture → 44100, 48000
#   |_ Altset 2 → 18ch playback / 16ch capture → 88200, 96000
#   |_ Altset 3 → 10ch playback / 10ch capture → 176400, 192000
#   |_ All altsets: S24_3LE (24-bit packed)
#

monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-MOTU_UltraLite-mk5_$YOUR_DEVICE_SERIAL*"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
      }
    }
  }

  {
    matches = [
      {
       	node.name = "~alsa_output.usb-MOTU_UltraLite-mk5_$YOUR_DEVICE_SERIAL*"
      }
    ]
    actions = {
      update-props = {
        audio.channels        = 10
        audio.rate            = 176400
        audio.format          = "S24_3LE"
        api.alsa.period-size  = 1024
        api.alsa.multi-rate   = false
        session.suspend-timeout-seconds = 0
        node.pause-on-idle = false
        api.alsa.disable-batch = true
      }
    }
  }

  {
    matches = [
      {
       	node.name = "~alsa_output.usb-MOTU_UltraLite-mk5_$YOUR_DEVICE_SERIAL*"
      }
    ]
    actions = {
      update-props = {
        audio.channels        = 10
        audio.rate            = 176400
        audio.format          = "S24_3LE"
        api.alsa.period-size  = 1024
        api.alsa.multi-rate   = false
        session.suspend-timeout-seconds = 0
        node.pause-on-idle = false
        api.alsa.disable-batch = true
      }
    }
  }
]

